diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'), # http://127.0.0.1:8000/diary/
    path('add/',views.AddView.as_view(), name='add'), # http://127.0.0.1:8000/diary/add/
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'), # http://127.0.0.1:8000/diary/update/#
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'), # http://127.0.0.1:8000/diary/delete/#
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'), # http://127.0.0.1:8000/diary/detail/#
]

first/urls.py
from django.contrib import admin
from django.urls import path,include  # 変更

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),  # 追加
]

diary/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Day(models.Model):
    title = models.CharField('タイトル', max_length=100)
    text = models.TextField('本文')
    date = models.DateField('日付', default=timezone.now)
    

diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'
        

diary/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .forms import DayCreateForm
from .models import Day

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'diary/day_list.html'
    model = Day

class AddView(generic.CreateView):
    template_name = 'diary/day_form.html'
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class UpdateView(generic.UpdateView):
    template_name = 'diary/day_form.html'
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class DeleteView(generic.DeleteView):
    template_name = 'diary/day_confirm_delete.html'
    model = Day
    success_url = reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    template_name = 'diary/day_detail.html'
    model = Day

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello World</title>
  </head>
  <body>

    <div class="container">
      <nav class="nav nav-tabs">
        <a class="nav-link" href="{% url 'diary:index' %}">TOP</a>
        <a class="nav-link" href="{% url 'diary:add' %}">WRITE</a>
      </nav>
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}

<div class="alert alert-warning" role="alert">
    <strong>WARNING!</strong>deleted dairy cannot be recovered.
</div>

<form action="" method="POST">
    <table class="table">
        <tr>
            <th>DATE</th>
            <td>{{ day.date }}</td>
        </tr>
        <tr>
            <th>TITLE</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>CONTENT</th>
            <td>{{ day.text }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">DELETE</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}

<table class="table">
    <tr>
        <th>DATE</th>
        <td>{{ day.date }}</td>
    </tr>
    <tr>
        <th>TITLE</th>
        <td>{{ day.title }}</td>
    </tr>
    <tr>
        <th>CONTENT</th>
        <td>{{ day.text | linebreaksbr | urlize }}</td>
    </tr>
</table>
{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>DATE</th>
            <td>{{ form.date }}</td>
        </tr>
        <tr>
            <th>TITLE</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>CONTENT</th>
            <td>{{ form.text }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<center><h1> MY DAIRY</h1></center>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>TITLES</th>
            <th>DATE</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
            <td>{{ day.date }}</td>
            <td><a href="{% url 'diary:update' day.pk %}">UPDATE</a></td>
            <td><a href="{% url 'diary:delete' day.pk %}">DELETE</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}